config/routes.rb
require 'api_constraints'

Grammar::Application.routes.draw do

namespace :api, defaults: { format: 'json' } do
  scope module: :v1, constraints: ApiConstraints.new(version: 1, default: :true) do
    get "users/get_access_token" => "users#get_access_token"
    resources :settings
    resources :user_sessions
    resources :users
    resources :notifications do
      member do
        get 'mark_as_seen'
        get 'mark_as_read'
      end
    end
  end
end

  root to: "home#index"

  get "logout" => "user_sessions#destroy", :as => "logout"
  get "login" => "user_sessions#new", :as => "login"
  get "notifications/mark_all_as_read" => "notifications#mark_all_as_read"

  get "key_requests/list_friend_requests" => "key_requests#list_friend_requests"
  get "key_requests/send_friend_request" => "key_requests#send_friend_request"
  get "key_requests/accept_friend_request" => "key_requests#accept_friend_request"
  get "key_requests/ignore_friend_request" => "key_requests#ignore_friend_request"
  get "key_requests/remove_friend_request" => "key_requests#remove_friend_request"

  get "user_friends/remove_friend" => "user_friends#remove_friend"

  get "users/list_friends" => "users#list_friends"
  get "users/show_friend" => "users#show_friend"
  get "users/search_users_window" => "users#search_users_window"
  get "users/search_users" => "users#search_users"
  
  get "dashboard" => "dashboard#show"

  resources :settings
  resources :user_sessions
  resources :users
  resources :notifications do
    member do
      get 'mark_as_seen'
      get 'mark_as_read'
    end
  end
  resources :badges

end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :user
  attr_accessible :user_id, :content, :notification_type, :priority, :seen, :read

  module NotificationTypes
    RECEIVED_FRIEND_REQUEST = 0
    ACCEPT_FRIEND_REQUEST = 1
    BADGE_AWARDED = 2
  end

  module NotificationPriorities
    LOW = 0
    MEDIUM = 1
    HIGH = 2
  end

  NOTIFICATION_TYPES = { 0 => "Received Friend Request", 1 => "Accepted Fried Request", 2 => "Badge Awarded" }
  NOTIFICATION_PRIORITIES = { 0 => "Low", 1 => "Medium", 2 => "High" }

  def self.notifications_for_user(current_user)
    Notification.where(user_id: current_user.id).order('created_at DESC')
  end

  def self.num_unseen_notifications_for_user(current_user)
    if current_user
      Notification.where(user_id: current_user.id, seen: false).order('created_at DESC').count
    end
  end

  def self.num_unread_notifications_for_user(current_user)
    if current_user
      Notification.where(user_id: current_user.id, read: false).order('created_at DESC').count
    end
  end

  def self.unread_notifications_for_user(current_user)
    if current_user
      res = Notification.where(user_id: current_user.id, read: false).order('created_at DESC')
      res
    end
  end

  def self.create_notification(user_id, content, type, priority)
    notification = Notification.new
    notification.user_id = user_id
    notification.content = content
    notification.notification_type = type
    notification.priority = priority
    notification.seen = false
    notification.read = false
    notification.save
  end

  def self.users_to_notify(current_user, project, include_admin)
    user_ids = []

    #fill user_ids

    if include_admin
      admin_user_ids = User.joins(:roles).where('roles.name' => 'Admin').pluck(:id)
      user_ids.concat(admin_user_ids)
    end
    user_ids.uniq!
    user_ids = user_ids - [current_user.id]
  end

  def title
    if !notification_type
      puts 'SOMETHING WENT WRONG'
      return ""
    end
    
    NOTIFICATION_TYPES[notification_type]
  end
  
  def self.received_friend_request_notification(for_user, from_user)
    content = "You have received a friend request from #{from_user.username}."
    create_notification(for_user.id, content, NotificationTypes::RECEIVED_FRIEND_REQUEST, NotificationPriorities::LOW)
  end
  
  def self.accepted_friend_request_notification(for_user, from_user)
    content = "#{from_user.username} has accepted your friend request."
    create_notification(for_user.id, content, NotificationTypes::ACCEPT_FRIEND_REQUEST, NotificationPriorities::LOW)
  end
  
  def self.badge_awarded_notification(for_user, badge)
    content = "You have earnt a #{Badge::BADGE_LEVELS[badge.level]} Badge!\n\n #{badge.name} \n\n #{badge.description}"
    create_notification(for_user.id, content, NotificationTypes::BADGE_AWARDED, NotificationPriorities::LOW)
  end


end

app/controllers/api/v1/notifications_controller.rb
module Api
  module V1
    class NotificationsController < ApplicationController
      
    end
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController

  filter_access_to :all, :except => [:mark_all_as_read]

  def index
    @notifications = Notification.notifications_for_user(@current_user)
  end

  def show
    @notification = Notification.find(params[:id])
  end

  def edit
    @notification = Notification.find(params[:id])
  end

  def update
    @notification = Notification.find(params[:id])

    if @notification.update_attributes(params[:notification])
      redirect_to @notification, notice: 'Notification was successfully updated.'
    else
      render action: "edit"
    end
  end

  def mark_as_seen
    @notification = Notification.find(params[:id])
    @notification.seen = true
    @notification.save

    render layout: false, locals: { klass: params[:klass], seen: @notification.seen }
  end

  def mark_as_read
    @notification = Notification.find(params[:id])
    @notification.seen = true
    @notification.read = true
    @notification.save
    @notifications_count = Notification.unread_notifications_for_user(current_user).count
    @js_action = params[:js_action]

    render layout: false, locals: { klass: params[:klass], seen: (@notification.read == true ? "Yes" : "No") }
  end

  def mark_all_as_read
    Notification.all.each do |notification|
      notification.seen = true
      notification.read = true
      notification.save
    end

    redirect_to notifications_path 
  end

end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_form.html.erb
<%= form_for(@notification) do |f| %>
  <% if @notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notification.errors.count, "error") %> prohibited this notification from being saved:</h2>

      <ul>
      <% @notification.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notifications/_notification_list.html.erb
<div class="notifications-window notifications-outer-window notifications-right notifications-absolute" style="display: none;">
	
	<div class="notifications-window notifications-inner-window">
	
	<% if unseen_notifications && unseen_notifications.count > 0 %>
	
		<% unseen_notifications.each do |notification| %>
			<% read_class = notification.read ? "" : "notifications-unread" %>
			<% klass = rand(10000) %>
			
			<div class="notifications-notification <%= klass %> <%=read_class%>">
				<div class="notifications-button notifications-info" style="display: block;">
					<%= notification.title %>
				</div>
				<div class="notifications-popup" style="max-height: 421px; right: 350px; display: none; padding-right: 40px;"> 
					<div class="row">
							<b>Message:</b></br>
							<%= notification.content %>
					</div>
					</br>
					<div class="row">
						<b>Received at:</b></br>
						<%= notification.created_at %>
					</div>
					</br>
					<div class="row">
						<% if !notification.read %>
						<%= link_to "Mark as Read", mark_as_read_notification_path(id: notification.id, klass: klass, js_action: 'hide'), remote: true, class: "button radius tiny secondary" %>
						<% end %>
					</div>
				</div>
			</div>
		<% end %>
	
	<% else %>
		<div class="notifications-notification">
			<div class="notifications-button notifications-info" style="display: block;">
				No new notifications
			</div>
		</div>
	<% end %>
	
	</div>
	
	<div class="notifications-notification notifications-radius">
		<div class="notifications-button" style="display: block;">
			<% num_new = Notification.num_unread_notifications_for_user(@current_user) %>
			<a href="/notifications" id="notifications-view-all">View All Notifications (<span id="notifications-view-all-number"><%= "#{num_new}" %></span> new)</a>
		</div>
	</div>
	
	
</div>

app/views/notifications/edit.html.erb
<h1>Editing notification</h1>

<%= render 'form' %>

<%= link_to 'Show', @notification %> |
<%= link_to 'Back', notifications_path %>

app/views/notifications/index.html.erb
<% title "Notifications" %>

<div class="row">
<h1>All Notifications</h1>

<%= link_to "Mark all as Read", notifications_mark_all_as_read_path(), class: "button tiny" %>

<table>
  <tr>
		<th>Content</th>
		<th>Type</th>
		<th>Priority</th>
		<th>Read</th>
		<th></th>
  </tr>

<% @notifications.each do |notification| %>
	<% klass = rand(10000) %>
  <tr class="table_row">
		<td><%= notification.content %></td>
		<td><%= Notification::NOTIFICATION_TYPES[notification.notification_type] %></td>
		<td><%= Notification::NOTIFICATION_PRIORITIES[notification.priority] %></td>
		<td class="<%= klass %> read_column"><%= notification.read ? "Yes" : "No" %></td>
		<td>
			<% if !notification.read %>
				<%= link_to "Mark as Read", mark_as_read_notification_path(id: notification.id, klass: klass, js_action: 'update'), remote: true, class: "button tiny" %>
			<% end %>
		</td>
  </tr>
<% end %>
</table>

<%= link_to "Mark all as Read", notifications_mark_all_as_read_path(), class: "button tiny" %>

<br />
</div>

app/views/notifications/mark_as_read.js.erb
$(".<%= klass %>.notifications-notification").hide(200, 'swing')
$(".<%= klass %>.notifications-notification").html("")
$(".<%= klass %>.read_column").html("<%=seen%>")
$(".<%= klass %>.read_column").closest(".table_row").find(".button").hide()

//TODO: Return number of seen and read notifications to update the views properly
num_notifications = $("#notifications_link").html()
if(num_notifications && num_notifications != "") {
	num = parseInt(num_notifications)
	if(num > 0) {
		num -= 1
	}
	num_notifications = num
	$("#notifications_link").html(num_notifications)
}

all_notifications_link = $("#notifications-view-all-number").html()
if(all_notifications_link && all_notifications_link != "") {
	num = parseInt(all_notifications_link)
	if(num > 0) {
		num -= 1
	}
	all_notifications_link = num
	$("#notifications-view-all-number").html(all_notifications_link)
}

count = <%=@notifications_count.to_i%>
if (count <= 0)
{
	console.log("count is 0")
	$("#notifications_link").css('background-image', 'url(/assets/folder_empty_icon.png)');
}

app/views/notifications/mark_as_seen.js.erb
$(".<%= klass %>").html(<%= seen %>)

app/views/notifications/new.html.erb
<h1>New notification</h1>

<%= render 'form' %>

<%= link_to 'Back', notifications_path %>

app/views/notifications/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_notification_path(@notification) %> |
<%= link_to 'Back', notifications_path %>