config/routes.rb
require 'api_constraints'

Grammar::Application.routes.draw do

namespace :api, defaults: { format: 'json' } do
  scope module: :v1, constraints: ApiConstraints.new(version: 1, default: :true) do
    get "users/get_access_token" => "users#get_access_token"
    resources :settings
    resources :user_sessions
    resources :users
    resources :notifications do
      member do
        get 'mark_as_seen'
        get 'mark_as_read'
      end
    end
  end
end

  root to: "home#index"

  get "logout" => "user_sessions#destroy", :as => "logout"
  get "login" => "user_sessions#new", :as => "login"
  get "notifications/mark_all_as_read" => "notifications#mark_all_as_read"

  get "key_requests/list_friend_requests" => "key_requests#list_friend_requests"
  get "key_requests/send_friend_request" => "key_requests#send_friend_request"
  get "key_requests/accept_friend_request" => "key_requests#accept_friend_request"
  get "key_requests/ignore_friend_request" => "key_requests#ignore_friend_request"
  get "key_requests/remove_friend_request" => "key_requests#remove_friend_request"

  get "user_friends/remove_friend" => "user_friends#remove_friend"

  get "users/list_friends" => "users#list_friends"
  get "users/show_friend" => "users#show_friend"
  get "users/search_users_window" => "users#search_users_window"
  get "users/search_users" => "users#search_users"
  
  get "dashboard" => "dashboard#show"

  resources :settings
  resources :user_sessions
  resources :users
  resources :notifications do
    member do
      get 'mark_as_seen'
      get 'mark_as_read'
    end
  end
  resources :badges

end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic
  extend FriendlyId
  friendly_id :username
  validates_format_of :username, :with => /^[A-Za-zd_]+$/
  attr_accessible :email, :password, :username, :password_confirmation, :first_name, :last_name, :caption, :about_me, :points
  has_many :user_roles
  has_many :roles, through: :user_roles
  has_many :key_requests
  has_many :user_friends
  has_many :friends, through: :user_friends, class_name: "User", source: :friend
  has_one :setting
  has_many :user_badges
  has_many :badges, through: :user_badges
  
  def role_symbols
    roles.map do |role|
      role.name.underscore.to_sym
    end
  end

  def has_friend_request_with?(friend)
    (KeyRequest.where(user_id: id, to_user_id: friend.id).count != 0) || (KeyRequest.where(user_id: friend.id, to_user_id: id).count != 0)
  end
  
  def is_friends_with(user)
    friends.include?(user)
  end
  
  def can_send_friend_request_to_user(user)
    if self == user
      return false
    elsif self.is_friends_with(user)
      return false
    elsif !user.setting.accept_friend_reqests
      return false
    else
      return true
    end
  end
  
  def can_see_users_profile?(user)
    if !is_friends_with(user) && !user.setting.public_profile
      return false
    end
    return true
  end
  
  def has_complete_profile
    complete = self.email != nil && self.email != ""
    complete = complete && self.first_name != nil && self.first_name != ""
    complete = complete && self.last_name != nil && self.last_name != ""
    complete = complete && self.caption != nil && self.caption != ""
    complete = complete && self.about_me != nil && self.about_me != ""
  end
  
end

app/controllers/api/v1/users_controller.rb
module Api
  module V1
    class UsersController < ApplicationController
      
      respond_to :json
      before_filter :restrict_access, except: [:get_access_token]

      def get_access_token
        user_session = UserSession.new
        user_session.username = params[:username]
        user_session.password = params[:password]
        if user_session.valid?
          user = User.find_by_username(params[:username])
          if !user.api_key
            user.generate_api_key
            user.save
          end
          render json: user
        else
          render json: user_session.errors, status: 401
        end
      end
      
      def show
        render json: current_user
      end
      
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  filter_resource_access

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])

    if @user != current_user
      if !current_user.can_see_users_profile?(@user)
        redirect_to root_url, flash: { error: "You are not friends with this user and their profile is not public." }
        return false
      else
        render 'show_public'
        return true
      end
    else
      
      @is_remote = true
      @friends = current_user.friends.order(:username)
      @user_settings = nil
      @sent_requests = KeyRequest.sent_friend_requests_for_user(current_user)
      @received_requests = KeyRequest.received_friend_requests_for_user(current_user)
      @setting = @user.setting
      @badges = @user.badges.order(:level)
    end
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
    @is_remote = false
  end

  def create
    @user = User.new(params[:user])
    @user.roles << Role.find_by_name(:user)
    @user.build_setting
    @user.setting.set_defaults
    @user.points = 0
    
    if @user.save
      
      Badge.award_badge(@user, Badge::BadgeTypes::SIGN_UP)
      
      redirect_to root_url, notice: 'Registration successful.'
    else
      render action: "new"
    end
  end

  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        
        if @user.has_complete_profile
          badge_earnt = Badge.award_badge(@user, Badge::BadgeTypes::COMPLETE_PROFILE)
        end
        @badges_earnt = [badge_earnt]
        
        format.html { redirect_to @user, notice: 'Successfully updated profile.' }
        format.js { render layout: false }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.delete

    redirect_to users_url
  end

  def list_friends
    @friends = current_user.friends
  end

  def search_users_window
    render layout: false
  end

  def search_users
    @users = []
    if params[:search] && params[:search] != "" && params[:search].gsub(" ", "") != ""
      @users = User.where('username ILIKE ?', "%#{params[:search]}%").joins(:setting).where("settings.show_in_search" => true)
    end

    render layout: false
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user, remote: @is_remote) do |f| %>
	<% if @user.errors.any? %>
	<div id="error_explanation" class="row">
		<h2><%= pluralize(@user.errors.count, "error") %> prohibited this action:</h2>
			<ul>
				<% @user.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
				<% end %>
			</ul>
	</div>
	<% end %>

	<div class="row">
		<div class="small-3 columns">
			<%= f.label :username %>
		</div>
		<div class="small-3 columns">
			<%= f.text_field :username, disabled: f.object.id ? true : false, class: "username_field" %>
		</div>
		<div class="small-3 columns">
		</div>
	</div>
	
	<div class="row">
		<div class="small-3 columns">
			<%= f.label :email %>
		</div>
		<div class="small-3 columns">
			<%= f.text_field :email %>
		</div>
		<div class="small-3 columns">
		</div>
	</div>
	
	<% password_fields_hidden = "" %>
	<% if f.object.id %>
		<% password_fields_hidden = "display:none;" %>
	<% end %>
	<div class="password_fields" style="<%=password_fields_hidden%>">
		<div class="row">
			<div class="small-3 columns">
				<%= f.label :password %>
			</div>
			<div class="small-3 columns user_password">
				<%= f.password_field :password %>
			</div>
			<div class="small-3 columns">
			</div>
		</div>
		
		<div class="row">
			<div class="small-3 columns">
				<%= f.label :password_confirmation, "Password confirmation" %>
			</div>
			<div class="small-3 columns user_password_confirmation">
				<%= f.password_field :password_confirmation %>
			</div>
			<div class="small-3 columns">
			</div>
		</div>
	</div>
	
	<% if f.object.id %>
		<%= link_to "Toggle Password Fields", "#", id: "change_password_button", class: "button secondary tiny" %>
	<% end %>
	
	</br></br>
	
	<% if f.object.id %>
		<div class="row">
			<div class="small-3 columns">
				<%= f.label :first_name %>
			</div>
			<div class="small-3 columns">
				<%= f.text_field :first_name %>
			</div>
			<div class="small-3 columns">
			</div>
		</div>
		
		<div class="row">
			<div class="small-3 columns">
				<%= f.label :last_name %>
			</div>
			<div class="small-3 columns">
				<%= f.text_field :last_name %>
			</div>
			<div class="small-3 columns">
			</div>
		</div>
		
		<div class="row">
			<div class="small-3 columns">
				<%= f.label :caption %>
			</div>
			<div class="small-9 columns">
				<%= f.text_field :caption %>
			</div>
		</div>
		
		<div class="row">
			<div class="small-3 columns">
				<%= f.label :about_me %>
			</div>
			<div class="small-9 columns">
				<%= f.text_area :about_me %>
			</div>
		</div>
	<% end %>
	
	<div class="row">
		<div class="small-3 columns">
			<% if f.object.id %>
				<%= f.submit "Save", class: "button", id: "save_profile_button" %>
			<% else %>
				<%= f.submit "Register", class: "button" %>
			<% end %>
		</div>
		<div class="small-3 columns">
			<% if @is_remote %>
				<%= link_to "Cancel", "#", id: "cancel_button", class: "button" %>
			<% end %>
		</div>
		<div class="small-3 columns">
		</div>
	</div>
	<% end %>

app/views/users/_my_friends.html.erb
<% @friends.each do |friend| %>
Name: <%= friend.username %>
<% end %>

<% if @friends.count == 0 %>
<div class="row">
	You have no friends :c
</div>
<% end %>

</br></br></br>

<div class="row centered">
	<%= link_to "Search for a Friend", users_search_users_window_path(id: @user.id), remote: true, class: "button" %>
</div>

<div class="row received_requests_title" style="<%=@received_requests.count > 0 ? "" : "display:none;"%>">
	<h4>
		Received Friend Requests
	</h4>
</div>

<div class="row received_requests_list">
	<% @received_requests.each do |fr| %>
		<%= render 'key_requests/sent_request_list_row', request: fr, type: :received %>
	<% end %>
</div>

<div class="row sent_requests_title" style="<%=@sent_requests.count > 0 ? "" : "display:none;"%>">
	<h4>
		Sent Friend Requests
	</h4>
</div>

<div class="row sent_requests_list">
	<% @sent_requests.each do |fr| %>
		<%= render 'key_requests/sent_request_list_row', request: fr, type: :sent %>
	<% end %>
</div>

app/views/users/_settings.html.erb
settings

app/views/users/_user_details.html.erb
<div class="row">
	<div class="small-3 columns">
		Username
	</div>
	<div class="small-3 columns user_username">
		<%= @user.username %>
	</div>
	<div class="small-3 columns">
	</div>
</div>
</br>

<div class="row">
	<div class="small-3 columns">
		Email
	</div>
	<div class="small-3 columns user_email">
		<%= @user.email %>
	</div>
	<div class="small-3 columns">
	</div>
</div>
</br>

<div class="row">
	<div class="small-3 columns">
		First name
	</div>
	<div class="small-3 columns user_first_name">
		<%= @user.first_name %>
	</div>
	<div class="small-3 columns">
	</div>
</div>
</br>

<div class="row">
	<div class="small-3 columns">
		Last name
	</div>
	<div class="small-3 columns user_last_name">
		<%= @user.last_name %>
	</div>
	<div class="small-3 columns">
	</div>
</div>
</br>

<div class="row">
	<div class="small-3 columns">
		Caption
	</div>
	<div class="small-9 columns user_caption">
		<%= @user.caption %>
	</div>
</div>
</br>

<div class="row">
	<div class="small-3 columns">
		About me
	</div>
	<div class="small-9 columns user_about_me">
		<%= @user.about_me %>
	</div>
</div>

</br></br></br></br>

<div class="row">
	<div class="small-3 columns">
		Points
	</div>
	<div class="small-9 columns">
		<%= @user.points %>
	</div>
</div>
</br>

<div class="row">
	<div class="small-3 columns">
		Friends
	</div>
	<div class="small-9 columns">
		<%= @user.friends.count %>
	</div>
</div>
</br>

<div class="row">
	<div class="small-3 columns">
		Badges
	</div>
	<div class="small-1 columns">
		<%= @user.badges.count %>
	</div>
	<div class="small-8 columns">
		
	</div>
</div>

</br></br></br></br></br></br></br>

<div class="row centered">
	<%= link_to 'Edit Profile', edit_user_path(@user), class: "button", id: "edit_profile_button" %>
</div>

app/views/users/_users_search.html.erb
<div class="facebox_title" style="background: #444444; width: 450px;">
	Search
</div>

</br>

<%= form_tag "search_users", method: 'get', remote: true, id: "search_users_form" do %>
	<%= hidden_field_tag :id, user_id %>
	<div class="row">
		<div class="small-2 columns">
			<%= label_tag :search, "Username" %>
		</div>
		<div class="small-5 columns">
			<%= text_field_tag :search, params[:search], class: "user_search_field" %>
		</div>
		<div class="small-3 columns">
			<%= submit_tag "Search", name: nil, class: "button tiny" %>
		</div>
		<div class="small-3 columns">
		</div>
	</div>
<% end %>

<div class="facebox_title" style="background: #444444; width: 450px;">
	Results
</div>

</br>

</br>

<div class="row users_table">
	No results.
</div>

app/views/users/edit.html.erb
<div class="row">
	<h1>Edit my profile</h1>
</div>
</br>

<%= render 'form' %>

<div class="row">
<%= link_to 'Show', @user %> |
<%= link_to 'Back', @user %>
</div>

app/views/users/index.html.erb
<div class="row">
	<h1>Listing users</h1>
</div>
</br>

<div class="row">
	<table>
		<tr>
			<th>Username</th>
			<th>Email</th>
			<th></th>
			<th></th>
			<th></th>
		</tr>

		<% @users.each do |user| %>
		<tr>
			<td><%= user.username %></td>
			<td><%= user.email %></td>
			<td><%= link_to 'Show', user %></td>
			<td><%= link_to 'Edit', edit_user_path(user) %></td>
			<td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		</tr>
		<% end %>
	</table>
</div>

</br>

<div class="row">
	<%= link_to 'New User', new_user_path, class: "button" %>
</div>

app/views/users/new.html.erb
<div class="row">
	<h1>Register</h1>
</div>
<br>
<%= render 'form' %>

<div class="row">
	<%= link_to 'Back', root_path, class: "button tiny secondary" %>
</div>

app/views/users/search_users.js.erb
$('.users_table').html('<%= escape_javascript(render :partial => 'search_users_results', locals: { users: @users }) %>')

app/views/users/search_users_window.js.erb
$.facebox('<%= escape_javascript(render :partial => 'users_search', locals: { user_id: @user.id }) %>')
$(".user_search_field").focus()

app/views/users/show.html.erb
<% title "#{@current_user.username}" %>

<div class="row">
	<div class="left-nav-top-bar">
		<h1 class="nav_top_title"></h1>
	</div>
	<div class="left-nav">
		<div class="left-nav-title">
			Menu
		</div>
		
		<div class="left-nav-list-area">
			<ul class="left-nav-list">
				<li><%= link_to "My Profile", "#", id: "nav_my_profile" %></li>
				<li><%= link_to "My Friends", "#", id: "nav_my_friends" %></li>
				<li><%= link_to "My Badges", "#", id: "nav_my_badges" %></li>
				<li><%= link_to "Settings", "#", id: "nav_settings" %></li>
			</ul>
		</div>
	</div>
	<div class="main-section">
		
		</br></br>

		<div class="content show_profile" style="display:none;">
			<%= render 'user_details' %>
		</div>
		
		<div class="content edit_profile" style="display:none;">
			<%= render 'form' %>
		</div>
		
		<div class="content my_friends" style="display:none;">
			<%= render 'user_friends/my_friends' %>
		</div>
		
		<div class="content my_badges" style="display:none;">
			<%= render 'user_badges/my_badges' %>
		</div>
		
		<div class="content settings" style="display:none;">
			<%= render 'settings/form' %>
		</div>

	</div>
</div>

<div class="row">
	<%= link_to 'Back', root_path, class: "button tiny secondary" %>
</div>

app/views/users/show_friend.html.erb
</br>
<div class="row">
	<h3>
		<%= @friend.username.titlecase.possessive + " Profile" %>
	</h3>
</div>
</br>

<div class="row">
	<div class="small-3 columns">
		Joined on:
	</div>
	<div class="small-3 columns">
		<%= @friend.created_at.strftime("%d/%m/%Y") %>
	</div>
	<div class="small-3 columns">
	</div>
</div>
</br>

<div class="row">
	<div class="small-3 columns">
		First name
	</div>
	<div class="small-3 columns user_first_name">
		<%= @friend.first_name %>
	</div>
	<div class="small-3 columns">
	</div>
</div>
</br>

<div class="row">
	<div class="small-3 columns">
		Last name
	</div>
	<div class="small-3 columns user_last_name">
		<%= @friend.last_name %>
	</div>
	<div class="small-3 columns">
	</div>
</div>
</br>

<div class="row">
	<div class="small-3 columns">
		Caption
	</div>
	<div class="small-9 columns user_caption">
		<%= @friend.caption %>
	</div>
</div>
</br>

<div class="row">
	<div class="small-3 columns">
		About me
	</div>
	<div class="small-9 columns user_about_me">
		<%= @friend.about_me %>
	</div>
</div>

app/views/users/show_public.html.erb
<% title "#{@user.username}" %>

</br>
<div class="row">
	<h3>
		<%= @user.username.titlecase.possessive + " Profile" %>
	</h3>
</div>
</br>

<div class="row">
	<div class="small-3 columns">
		Joined on:
	</div>
	<div class="small-3 columns">
		<%= @user.created_at.strftime("%d/%m/%Y") %>
	</div>
	<div class="small-3 columns">
	</div>
</div>
</br>

<div class="row">
	<div class="small-3 columns">
		First name
	</div>
	<div class="small-3 columns user_first_name">
		<%= @user.first_name %>
	</div>
	<div class="small-3 columns">
	</div>
</div>
</br>

<div class="row">
	<div class="small-3 columns">
		Last name
	</div>
	<div class="small-3 columns user_last_name">
		<%= @user.last_name %>
	</div>
	<div class="small-3 columns">
	</div>
</div>
</br>

<div class="row">
	<div class="small-3 columns">
		Caption
	</div>
	<div class="small-9 columns user_caption">
		<%= @user.caption %>
	</div>
</div>
</br>

<div class="row">
	<div class="small-3 columns">
		About me
	</div>
	<div class="small-9 columns user_about_me">
		<%= @user.about_me %>
	</div>
</div>

</br></br></br></br></br></br>

<% if @current_user.is_friends_with(@user) %>
	<div class="row">
		<%= link_to "Unfriend", user_friends_remove_friend_path(friend_id: @user.id), data: { confirm: 'Unfriend for real? :c' }, class: "button secondary tiny" %>
	</div>
<% end %>

app/views/users/update.js.erb
$('.user_username').text("<%=@user.username%>")
$('.user_email').text("<%=@user.email%>")
$('.user_first_name').text("<%=@user.first_name%>")
$('.user_last_name').text("<%=@user.last_name%>")
$('.user_caption').text("<%=raw @user.caption%>")
$('.user_about_me').text("<%=raw @user.about_me%>")

$('#user_password').val("")
$('#user_password_confirmation').val("")


$('.has_focus').hide(200, 'swing')
$('.has_focus').removeClass('has_focus')

$('.show_profile').addClass('has_focus')
$('.show_profile').show(200, 'swing')

<%= render 'user_badges/update_badges', badges_earnt: @badges_earnt %>