config/routes.rb
require 'api_constraints'

Grammar::Application.routes.draw do

namespace :api, defaults: { format: 'json' } do
  scope module: :v1, constraints: ApiConstraints.new(version: 1, default: :true) do
    get "users/get_access_token" => "users#get_access_token"
    resources :settings
    resources :user_sessions
    resources :users
    resources :notifications do
      member do
        get 'mark_as_seen'
        get 'mark_as_read'
      end
    end
  end
end

  root to: "home#index"

  get "logout" => "user_sessions#destroy", :as => "logout"
  get "login" => "user_sessions#new", :as => "login"
  get "notifications/mark_all_as_read" => "notifications#mark_all_as_read"

  get "key_requests/list_friend_requests" => "key_requests#list_friend_requests"
  get "key_requests/send_friend_request" => "key_requests#send_friend_request"
  get "key_requests/accept_friend_request" => "key_requests#accept_friend_request"
  get "key_requests/ignore_friend_request" => "key_requests#ignore_friend_request"
  get "key_requests/remove_friend_request" => "key_requests#remove_friend_request"

  get "user_friends/remove_friend" => "user_friends#remove_friend"

  get "users/list_friends" => "users#list_friends"
  get "users/show_friend" => "users#show_friend"
  get "users/search_users_window" => "users#search_users_window"
  get "users/search_users" => "users#search_users"
  
  get "dashboard" => "dashboard#show"

  resources :settings
  resources :user_sessions
  resources :users
  resources :notifications do
    member do
      get 'mark_as_seen'
      get 'mark_as_read'
    end
  end
  resources :badges

end

app/models/key_request.rb
class KeyRequest < ActiveRecord::Base
  belongs_to :user
  attr_accessible :expire_date, :key, :accepted, :accepted_date, :key_request_type, :to_user_id, :ignored
  validates_presence_of :expire_date, :key, :key_request_type, :to_user_id

  module KeyRequestType
    FRIEND_REQUEST = 0
    EMAIL_VERIFICATION = 1
  end

  module RequestResult
    SUCCESS = 0
    ERROR = 1
    REQUEST_EXPIRED = 2
    REQUEST_ALREADY_USED = 3
  end

  def generate_key
    begin
      self.key = SecureRandom.hex
    end while self.class.exists?(key: key)
  end

  def self.generate_friend_request(user, friend)
    if !user.has_friend_request_with?(friend)
      kr = KeyRequest.new
      kr.user_id = user.id
      kr.to_user_id = friend.id
      kr.key_request_type = KeyRequestType::FRIEND_REQUEST
      kr.expire_date = Date.current + 30.days
      kr.accepted = false
      kr.generate_key
      kr.ignored = false
      kr.save
      
      Notification.received_friend_request_notification(friend, user)
      
      kr
    else
      return nil
    end
  end

  def accept_friend_request
    if expire_date < Date.current
      return { error: RequestResult::REQUEST_EXPIRED }
    end

    if accepted
      return { error: RequestResult::REQUEST_ALREADY_USED }
    end

    if UserFriend.add_friend(user_id, to_user_id)
      self.accepted_date = Date.current
      self.accepted = true
      
      user_1 = User.find(user_id)
      user_2 = User.find(to_user_id)
      
      Notification.accepted_friend_request_notification(user_1, user_2)
      
      Badge.add_friend_badge(user_1)
      current_users_badge = Badge.add_friend_badge(user_2)
      
      if self.save!
        return { result: true, badge: current_users_badge }
      end
      
    else
      return error { RequestResult::ERROR }
    end
  end

  def remove_friend_request
    self.destroy
  end
  
  def ignore_friend_request
    self.ignored = true
    self.save
  end

  def self.sent_friend_requests_for_user(user)
    KeyRequest.where(key_request_type: KeyRequest::KeyRequestType::FRIEND_REQUEST, user_id: user.id, accepted: false)
  end
  
  def self.received_friend_requests_for_user(user)
    KeyRequest.where(key_request_type: KeyRequest::KeyRequestType::FRIEND_REQUEST, to_user_id: user.id, accepted: false, ignored: [false, nil])
  end

end

app/controllers/api/v1/key_requests_controller.rb
module Api
  module V1
    class KeyRequestsController < ApplicationController
      
    end
  end
end

app/controllers/key_requests_controller.rb
class KeyRequestsController < ApplicationController

  filter_access_to :all, except: [:send_friend_request]

  def list_friend_requests
    @key_requests = KeyRequest.list_friend_requests_for_user(current_user)
  end

  def send_friend_request
    @request = KeyRequest.generate_friend_request(current_user, User.find(params[:friend_id]))
    @user_id = params[:friend_id]
  end

  def accept_friend_request
    @key_request = KeyRequest.find(params[:id])
    result = @key_request.accept_friend_request
    @friend = @key_request.user
    @num_received_requests = KeyRequest.received_friend_requests_for_user(current_user).count
    @badges_earnt = [result[:badge]]
  end

  def ignore_friend_request
    @key_request = KeyRequest.find(params[:id])
    @key_request.ignore_friend_request
    @num_received_requests = KeyRequest.received_friend_requests_for_user(current_user).count
  end

  def remove_friend_request
    @key_request = KeyRequest.find(params[:id])
    @key_request_id = @key_request.id
    @key_request.remove_friend_request
    @num_sent_requests = KeyRequest.sent_friend_requests_for_user(current_user).count
  end
end

app/helpers/key_requests_helper.rb
module KeyRequestsHelper
end

app/views/key_requests/_request_list_row.html.erb
<div class="friend_row">
	<div class="small-3 columns">
		<% if type == :received %>
			<% friend = User.find(request.user_id) %>
		<% else %>
		<% friend = User.find(request.to_user_id) %>
		<% end %>

		<% if @current_user.can_see_users_profile?(friend) %>
			<%= link_to friend.username, users_show_friend_path(id: @current_user.id, friend_id: friend.id), class: "" %>
		<% else %>
			<%= friend.username %>
		<% end %>

	</div>
	<div class="small-3 columns">
		<%= request.created_at.strftime("%d/%m/%Y") %>
	</div>
	<div class="small-3 columns">
		<% if type == :received %>
			<%= link_to "Accept Friend Request", key_requests_accept_friend_request_path(id: request.id), remote: true, class: "button tiny request_#{request.id}" %>
		<% else %>
			&nbsp;
		<% end %>
	</div>
	<div class="small-3 columns">
		<% if type == :received %>
			<%= link_to "Ignore Friend Request", key_requests_ignore_friend_request_path(id: request.id), remote: true, class: "button tiny request_#{request.id}" %>
		<% elsif type == :sent %>
		<%= link_to "Revoke Friend Request", key_requests_remove_friend_request_path(id: request.id), remote: true, class: "button tiny request_#{request.id}" %>
		<% end %>
	</div>
	</br></br></br>
</div>

app/views/key_requests/_sent_request_list_row.html.erb
<div class="row">
	<div class="small-3 columns">
		<% friend = User.find(request.to_user_id) %>
		<%= friend.username %>
	</div>
	<div class="small-3 columns">
		<%= request.created_at.strftime("%d/%m/%Y") %>
	</div>
	<div class="small-3 columns">
		<% if type == :received %>
		<%= link_to "Accept Friend Request", "#", remote: true, class: "button tiny" %>
		<% end %>
	</div>
</div>

app/views/key_requests/accept_friend_request.js.erb
$(".no_friends_message").hide(200, "swing")
$(".request_<%=@key_request.id%>").closest(".friend_row").hide(200, "swing")
$(".friends_list").append("<%= escape_javascript(render(partial: 'user_friends/friends_list_row', locals: { friend: @friend }))%>")
if (<%=@num_received_requests%> == 0) {
	$(".received_requests_title").hide(200, "swing")
}

<%= render 'user_badges/update_badges', badges_earnt: @badges_earnt %>

app/views/key_requests/ignore_friend_request.js.erb
$(".request_<%=@key_request.id%>").closest(".friend_row").hide(200, "swing")
if (<%=@num_received_requests%> == 0) {
	$(".received_requests_title").hide(200, "swing")
}

app/views/key_requests/remove_friend_request.js.erb
$(".request_<%=@key_request.id%>").closest(".friend_row").hide(200, "swing")
if (<%=@num_sent_requests%> == 0) {
	$(".sent_requests_title").hide(200, "swing")
}

app/views/key_requests/send_friend_request.js.erb
<% if @request %>
	$(".send_friend_request_button_<%=@user_id%>").text("Sent!")
	$(".sent_requests_title").show(200, "swing")
	$(".sent_requests_list").append("<%= escape_javascript(render(partial: 'request_list_row', locals: { request: @request, type: :sent, current_user: @current_user }))%>")
<% end %>