config/routes.rb
require 'api_constraints'

Grammar::Application.routes.draw do

namespace :api, defaults: { format: 'json' } do
  scope module: :v1, constraints: ApiConstraints.new(version: 1, default: :true) do
    get "users/get_access_token" => "users#get_access_token"
    resources :settings
    resources :user_sessions
    resources :users
    resources :notifications do
      member do
        get 'mark_as_seen'
        get 'mark_as_read'
      end
    end
  end
end

  root to: "home#index"

  get "logout" => "user_sessions#destroy", :as => "logout"
  get "login" => "user_sessions#new", :as => "login"
  get "notifications/mark_all_as_read" => "notifications#mark_all_as_read"

  get "key_requests/list_friend_requests" => "key_requests#list_friend_requests"
  get "key_requests/send_friend_request" => "key_requests#send_friend_request"
  get "key_requests/accept_friend_request" => "key_requests#accept_friend_request"
  get "key_requests/ignore_friend_request" => "key_requests#ignore_friend_request"
  get "key_requests/remove_friend_request" => "key_requests#remove_friend_request"

  get "user_friends/remove_friend" => "user_friends#remove_friend"

  get "users/list_friends" => "users#list_friends"
  get "users/show_friend" => "users#show_friend"
  get "users/search_users_window" => "users#search_users_window"
  get "users/search_users" => "users#search_users"
  
  get "dashboard" => "dashboard#show"

  resources :settings
  resources :user_sessions
  resources :users
  resources :notifications do
    member do
      get 'mark_as_seen'
      get 'mark_as_read'
    end
  end
  resources :badges

end

app/models/user_friend.rb
class UserFriend < ActiveRecord::Base
  belongs_to :user, class_name: "User", foreign_key: "user_id"
  belongs_to :friend, class_name: "User", foreign_key: "friend_id"
  
  def self.add_friend(user_id, friend_id)
    user_friend = UserFriend.new
    user_friend.user_id = user_id
    user_friend.friend_id = friend_id
    user_result = user_friend.save
    
    user_friend = UserFriend.new
    user_friend.user_id = friend_id
    user_friend.friend_id = user_id
    friend_result = user_friend.save
    
    user_result && friend_result
  end
  
  def self.remove_friend(user_id, friend_id)
    user_friend = UserFriend.where(user_id: user_id, friend_id: friend_id).first
    if !user_friend
      user_friend = UserFriend.where(user_id: friend_id, friend_id: user_id).first
    end
    
    if user_friend
      user_friend.destroy
    end

    key_request = KeyRequest.where(user_id: user_id, to_user_id: friend_id).first
    if !key_request
      key_request = KeyRequest.where(user_id: friend_id, to_user_id: user_id).first
    end
    
    if key_request
      key_request.destroy
    end
  end
end

app/controllers/api/v1/user_friends_controller.rb
module Api
  module V1
    class UserFriendsController < ApplicationController
      
    end
  end
end

app/controllers/user_friends_controller.rb
class UserFriendsController < ApplicationController
  
  filter_access_to :all, except: [:remove_friend]

  def remove_friend
    if UserFriend.remove_friend(@current_user.id, params[:friend_id])
      redirect_to user_path(@current_user)
    end
  end
  
end

app/helpers/user_friends_helper.rb
module UserFriendsHelper
end

app/views/user_friends/_form.html.erb
<%= form_for(@user_friend) do |f| %>
  <% if @user_friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_friend.errors.count, "error") %> prohibited this user_friend from being saved:</h2>

      <ul>
      <% @user_friend.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_friends/_friends_list_row.html.erb
<div class="row">
	<%= friend.username %>
</div>
<div class="row">
	Joined: <%= friend.created_at.strftime("%d/%m/%Y") %>
</div>
<div class="row">
	<%= friend.caption %>
</div>

</br>

<div class="row">
	<%= link_to "View Profile", user_path(friend), class: "button tiny" %>
</div>

</br>

app/views/user_friends/_my_friends.html.erb
<div class="friends_list">
	<% @friends.each do |friend| %>
		<%= render "user_friends/friends_list_row", friend: friend %>
	<% end %>
</div>

<% if @friends.count == 0 %>
<div class="row no_friends_message">
	You have no friends :c
</div>
<% end %>

</br></br></br>

<div class="row centered">
	<%= link_to "Search for a Friend", users_search_users_window_path(id: @user.id), remote: true, class: "button" %>
</div>

<div class="row received_requests_title" style="<%=@received_requests.count > 0 ? "" : "display:none;"%>">
	<h4>
		Received Friend Requests
	</h4>
</div>

</br>

<div class="row received_requests_list">
	<% @received_requests.each do |fr| %>
		<%= render 'key_requests/request_list_row', request: fr, type: :received, current_user: current_user %>
	<% end %>
</div>

<div class="row sent_requests_title" style="<%=@sent_requests.count > 0 ? "" : "display:none;"%>">
	<h4>
		Sent Friend Requests
	</h4>
</div>

</br>

<div class="row sent_requests_list">
	<% @sent_requests.each do |fr| %>
		<%= render 'key_requests/request_list_row', request: fr, type: :sent, current_user: current_user %>
	<% end %>
</div>

app/views/user_friends/edit.html.erb
<h1>Editing user_friend</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_friend %> |
<%= link_to 'Back', user_friends_path %>

app/views/user_friends/index.html.erb
<h1>Listing user_friends</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @user_friends.each do |user_friend| %>
  <tr>
    <td><%= link_to 'Show', user_friend %></td>
    <td><%= link_to 'Edit', edit_user_friend_path(user_friend) %></td>
    <td><%= link_to 'Destroy', user_friend, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User friend', new_user_friend_path %>

app/views/user_friends/new.html.erb
<h1>New user_friend</h1>

<%= render 'form' %>

<%= link_to 'Back', user_friends_path %>

app/views/user_friends/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_user_friend_path(@user_friend) %> |
<%= link_to 'Back', user_friends_path %>